version: "3"
services:
  webhooks:
    build: .
    image: registry.cn-qingdao.aliyuncs.com/wangdali/webhooks
    container_name: webhooks
    environment:
      TZ: Asia/Shanghai
    networks:
      - codeforfun-net
    volumes:
      - "./target:/var/jenkins_home/workspace/codeforfun-webhooks/target"
networks:
  codeforfun-net:
    external:
      name: codeforfun-network